import type { ServiceRow, ServiceCategory } from "@/types/database";

// Extends the DB row with presentation-only fields.
// price_cents is the midpoint used for deposit math.
// priceDisplay is the range shown on the site ("$75–$110", "from $265", etc.)
export interface ServiceWithDisplay extends ServiceRow {
  priceDisplay: string;
  durationDisplay: string; // e.g. "60–75 min" or "45 min"
}

// Badge labels applied to select cards
export type ServiceBadge = "Most Booked" | "New" | "Consult Required";
export const serviceBadges: Partial<Record<string, ServiceBadge>> = {
  "balayage-partial": "Most Booked",
  "balayage-full": "Most Booked",
  "precision-cut": "Most Booked",
  "vivid-color": "Consult Required",
  "color-correction": "Consult Required",
  "bridal-day": "Consult Required",
  "wedding-party": "Consult Required",
  "tape-in-extensions": "Consult Required",
  "hand-tied-extensions": "Consult Required",
};

export const services: ServiceWithDisplay[] = [
  // ── CUTS ────────────────────────────────────────────────────────────────────
  {
    id: "00000000-0000-0000-0000-000000000001",
    slug: "precision-cut",
    name: "Precision Cut & Style Consultation",
    description:
      "Shampoo, scalp massage, personalized cut, blowout, and styling guidance.",
    category: "cuts" as ServiceCategory,
    duration_min: 68,
    price_cents: 9250,
    deposit_cents: 0,
    requires_consult: false,
    is_active: true,
    sort_order: 1,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$75–$110",
    durationDisplay: "60–75 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000002",
    slug: "mens-cut",
    name: "Signature Men's Cut",
    description:
      "Clipper or scissor cut tailored to your face shape, finished with product styling.",
    category: "cuts" as ServiceCategory,
    duration_min: 45,
    price_cents: 5750,
    deposit_cents: 0,
    requires_consult: false,
    is_active: true,
    sort_order: 2,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$45–$70",
    durationDisplay: "45 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000003",
    slug: "buzz-fade",
    name: "Buzz / Skin Fade",
    description: "Clean clipper cut with detailed fade and neckline.",
    category: "cuts" as ServiceCategory,
    duration_min: 30,
    price_cents: 4250,
    deposit_cents: 0,
    requires_consult: false,
    is_active: true,
    sort_order: 3,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$35–$50",
    durationDisplay: "30 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000004",
    slug: "beard-trim",
    name: "Beard Trim & Shape",
    description: "Hot towel, beard sculpting, and neckline cleanup.",
    category: "cuts" as ServiceCategory,
    duration_min: 25,
    price_cents: 3250,
    deposit_cents: 0,
    requires_consult: false,
    is_active: true,
    sort_order: 4,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$25–$40",
    durationDisplay: "20–30 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000005",
    slug: "cut-beard-combo",
    name: "The Combo (Cut + Beard)",
    description: "Signature cut paired with a beard trim and hot towel finish.",
    category: "cuts" as ServiceCategory,
    duration_min: 60,
    price_cents: 8000,
    deposit_cents: 0,
    requires_consult: false,
    is_active: true,
    sort_order: 5,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$65–$95",
    durationDisplay: "60 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000006",
    slug: "straight-shave",
    name: "Hot Towel Shave",
    description:
      "Traditional straight razor shave with hot towels and aftershave balm.",
    category: "cuts" as ServiceCategory,
    duration_min: 45,
    price_cents: 5750,
    deposit_cents: 0,
    requires_consult: false,
    is_active: true,
    sort_order: 6,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$45–$70",
    durationDisplay: "45 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000007",
    slug: "kids-cut",
    name: "Kids' Cut (12 & under)",
    description: "Patient, kid-friendly haircut.",
    category: "cuts" as ServiceCategory,
    duration_min: 30,
    price_cents: 3750,
    deposit_cents: 0,
    requires_consult: false,
    is_active: true,
    sort_order: 7,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$30–$45",
    durationDisplay: "30 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000008",
    slug: "bang-trim",
    name: "Bang Trim",
    description: "Quick fringe touch-up between full cuts.",
    category: "cuts" as ServiceCategory,
    duration_min: 15,
    price_cents: 2000,
    deposit_cents: 0,
    requires_consult: false,
    is_active: true,
    sort_order: 8,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$15–$25",
    durationDisplay: "15 min",
  },

  // ── COLOR ───────────────────────────────────────────────────────────────────
  {
    id: "00000000-0000-0000-0000-000000000009",
    slug: "single-process",
    name: "Single Process Color",
    description:
      "One uniform color from root to tip — covers gray or shifts your base.",
    category: "color" as ServiceCategory,
    duration_min: 105,
    price_cents: 12250,
    deposit_cents: 3063,
    requires_consult: false,
    is_active: true,
    sort_order: 1,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$95–$150",
    durationDisplay: "90–120 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000010",
    slug: "root-touchup",
    name: "Root Touch-Up",
    description:
      "Refreshes regrowth to match your existing color, every 4–6 weeks.",
    category: "color" as ServiceCategory,
    duration_min: 75,
    price_cents: 10000,
    deposit_cents: 0,
    requires_consult: false,
    is_active: true,
    sort_order: 2,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$80–$120",
    durationDisplay: "60–90 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000011",
    slug: "gloss",
    name: "Gloss / Toner",
    description:
      "Add-on or standalone — boosts shine, neutralizes brass, refreshes tone.",
    category: "color" as ServiceCategory,
    duration_min: 38,
    price_cents: 5750,
    deposit_cents: 0,
    requires_consult: false,
    is_active: true,
    sort_order: 3,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$45–$70",
    durationDisplay: "30–45 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000012",
    slug: "partial-highlights",
    name: "Partial Highlights",
    description:
      "Highlights around the face and crown for dimension without full commitment.",
    category: "color" as ServiceCategory,
    duration_min: 120,
    price_cents: 16500,
    deposit_cents: 4125,
    requires_consult: false,
    is_active: true,
    sort_order: 4,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$135–$195",
    durationDisplay: "90–150 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000013",
    slug: "full-highlights",
    name: "Full Highlights",
    description:
      "All-over foil highlights for maximum brightness and dimension.",
    category: "color" as ServiceCategory,
    duration_min: 165,
    price_cents: 23500,
    deposit_cents: 5875,
    requires_consult: false,
    is_active: true,
    sort_order: 5,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$185–$285",
    durationDisplay: "150–180 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000014",
    slug: "balayage-partial",
    name: "Balayage — Partial",
    description:
      "Hand-painted highlights around the face and ends for a lived-in look.",
    category: "color" as ServiceCategory,
    duration_min: 135,
    price_cents: 26000,
    deposit_cents: 6500,
    requires_consult: false,
    is_active: true,
    sort_order: 6,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$210–$310",
    durationDisplay: "120–150 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000015",
    slug: "balayage-full",
    name: "Balayage — Full",
    description:
      "Full hand-painted color for a seamless, low-maintenance grow-out.",
    category: "color" as ServiceCategory,
    duration_min: 210,
    price_cents: 35500,
    deposit_cents: 8875,
    requires_consult: false,
    is_active: true,
    sort_order: 7,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$285–$425",
    durationDisplay: "180–240 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000016",
    slug: "babylights",
    name: "Babylights",
    description:
      "Ultra-fine foil highlights for the most natural-looking brightness.",
    category: "color" as ServiceCategory,
    duration_min: 210,
    price_cents: 29000,
    deposit_cents: 7250,
    requires_consult: false,
    is_active: true,
    sort_order: 8,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$215–$365",
    durationDisplay: "180–240 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000017",
    slug: "frosted-tips",
    name: "Frosted Tips",
    description:
      "Bleached tips with a tonal finish — modern revival of the classic look.",
    category: "color" as ServiceCategory,
    duration_min: 75,
    price_cents: 12750,
    deposit_cents: 0,
    requires_consult: false,
    is_active: true,
    sort_order: 9,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$95–$160",
    durationDisplay: "60–90 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000018",
    slug: "ombre",
    name: "Ombré / Sombré",
    description: "Soft or dramatic gradient from a darker root to lighter ends.",
    category: "color" as ServiceCategory,
    duration_min: 180,
    price_cents: 28500,
    deposit_cents: 7125,
    requires_consult: false,
    is_active: true,
    sort_order: 10,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$210–$360",
    durationDisplay: "150–210 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000019",
    slug: "vivid-color",
    name: "Vivid / Fashion Color",
    description: "Pinks, blues, coppers, pastels — full consultation required.",
    category: "color" as ServiceCategory,
    duration_min: 180,
    price_cents: 34000,
    deposit_cents: 8500,
    requires_consult: true,
    is_active: true,
    sort_order: 11,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$215–$465",
    durationDisplay: "180+ min",
  },
  {
    id: "00000000-0000-0000-0000-000000000020",
    slug: "color-correction",
    name: "Color Correction",
    description:
      "For fixing previous color or major tonal shifts. Always quoted post-consult.",
    category: "color" as ServiceCategory,
    duration_min: 240,
    price_cents: 26500,
    deposit_cents: 6625,
    requires_consult: true,
    is_active: true,
    sort_order: 12,
    created_at: new Date(0).toISOString(),
    priceDisplay: "from $265",
    durationDisplay: "240+ min",
  },
  {
    id: "00000000-0000-0000-0000-000000000021",
    slug: "gray-blending",
    name: "Gray Blending",
    description:
      "Demi-permanent service that softens grays without full coverage.",
    category: "color" as ServiceCategory,
    duration_min: 75,
    price_cents: 12250,
    deposit_cents: 0,
    requires_consult: false,
    is_active: true,
    sort_order: 13,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$95–$150",
    durationDisplay: "60–90 min",
  },

  // ── TREATMENTS ──────────────────────────────────────────────────────────────
  {
    id: "00000000-0000-0000-0000-000000000022",
    slug: "deep-conditioning",
    name: "Deep Conditioning Treatment",
    description: "Hydrating mask for thirsty, color-treated, or damaged hair.",
    category: "treatments" as ServiceCategory,
    duration_min: 25,
    price_cents: 5000,
    deposit_cents: 0,
    requires_consult: false,
    is_active: true,
    sort_order: 1,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$40–$60",
    durationDisplay: "20–30 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000023",
    slug: "olaplex",
    name: "Olaplex Bond Repair",
    description: "Strengthens bonds during or after a color service.",
    category: "treatments" as ServiceCategory,
    duration_min: 20,
    price_cents: 5250,
    deposit_cents: 0,
    requires_consult: false,
    is_active: true,
    sort_order: 2,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$40–$65",
    durationDisplay: "+20 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000024",
    slug: "k18",
    name: "K18 Molecular Repair",
    description: "4-minute treatment that reverses damage at the molecular level.",
    category: "treatments" as ServiceCategory,
    duration_min: 15,
    price_cents: 6500,
    deposit_cents: 0,
    requires_consult: false,
    is_active: true,
    sort_order: 3,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$50–$80",
    durationDisplay: "+15 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000025",
    slug: "keratin",
    name: "Keratin Smoothing Treatment",
    description: "Frizz reduction and smoothing — lasts 3–5 months.",
    category: "treatments" as ServiceCategory,
    duration_min: 150,
    price_cents: 36500,
    deposit_cents: 9125,
    requires_consult: false,
    is_active: true,
    sort_order: 4,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$265–$465",
    durationDisplay: "120–180 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000026",
    slug: "brazilian-blowout",
    name: "Brazilian Blowout",
    description: "Customized smoothing treatment with no harsh fumes.",
    category: "treatments" as ServiceCategory,
    duration_min: 90,
    price_cents: 40000,
    deposit_cents: 10000,
    requires_consult: false,
    is_active: true,
    sort_order: 5,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$315–$485",
    durationDisplay: "90 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000027",
    slug: "scalp-detox",
    name: "Scalp Detox Treatment",
    description:
      "Exfoliation and scalp massage to clear buildup and stimulate growth.",
    category: "treatments" as ServiceCategory,
    duration_min: 30,
    price_cents: 7000,
    deposit_cents: 0,
    requires_consult: false,
    is_active: true,
    sort_order: 6,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$55–$85",
    durationDisplay: "30 min",
  },

  // ── STYLING ─────────────────────────────────────────────────────────────────
  {
    id: "00000000-0000-0000-0000-000000000028",
    slug: "blowout",
    name: "Express Blowout",
    description: "Wash, dry, and style — bouncy, sleek, or beachy.",
    category: "styling" as ServiceCategory,
    duration_min: 45,
    price_cents: 6750,
    deposit_cents: 0,
    requires_consult: false,
    is_active: true,
    sort_order: 1,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$55–$80",
    durationDisplay: "45 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000029",
    slug: "updo",
    name: "Special Occasion Styling",
    description:
      "Updos, braids, or down-styles for events, prom, photoshoots.",
    category: "styling" as ServiceCategory,
    duration_min: 75,
    price_cents: 13000,
    deposit_cents: 3250,
    requires_consult: false,
    is_active: true,
    sort_order: 2,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$95–$165",
    durationDisplay: "60–90 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000030",
    slug: "bridal-trial",
    name: "Bridal Hair (Trial)",
    description: "Pre-wedding trial to lock in your look.",
    category: "styling" as ServiceCategory,
    duration_min: 90,
    price_cents: 16500,
    deposit_cents: 4125,
    requires_consult: false,
    is_active: true,
    sort_order: 3,
    created_at: new Date(0).toISOString(),
    priceDisplay: "from $165",
    durationDisplay: "90 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000031",
    slug: "bridal-day",
    name: "Bridal Hair (Day-of)",
    description: "Day-of styling — on-location available.",
    category: "styling" as ServiceCategory,
    duration_min: 105,
    price_cents: 24500,
    deposit_cents: 6125,
    requires_consult: true,
    is_active: true,
    sort_order: 4,
    created_at: new Date(0).toISOString(),
    priceDisplay: "from $245",
    durationDisplay: "90–120 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000032",
    slug: "wedding-party",
    name: "Wedding Party Styling",
    description: "Group bookings — ask about packages.",
    category: "styling" as ServiceCategory,
    duration_min: 53,
    price_cents: 11500,
    deposit_cents: 2875,
    requires_consult: true,
    is_active: true,
    sort_order: 5,
    created_at: new Date(0).toISOString(),
    priceDisplay: "from $115/person",
    durationDisplay: "45–60 min/person",
  },

  // ── EXTENSIONS ──────────────────────────────────────────────────────────────
  {
    id: "00000000-0000-0000-0000-000000000033",
    slug: "tape-in-extensions",
    name: "Tape-In Extensions",
    description: "Semi-permanent, 6–8 week maintenance cycle.",
    category: "extensions" as ServiceCategory,
    duration_min: 150,
    price_cents: 41500,
    deposit_cents: 10375,
    requires_consult: true,
    is_active: true,
    sort_order: 1,
    created_at: new Date(0).toISOString(),
    priceDisplay: "from $415 + hair",
    durationDisplay: "120–180 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000034",
    slug: "hand-tied-extensions",
    name: "Hand-Tied Wefts",
    description:
      "Premium method for the most natural feel — long-term wear.",
    category: "extensions" as ServiceCategory,
    duration_min: 210,
    price_cents: 81500,
    deposit_cents: 20375,
    requires_consult: true,
    is_active: true,
    sort_order: 2,
    created_at: new Date(0).toISOString(),
    priceDisplay: "from $815 + hair",
    durationDisplay: "180–240 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000035",
    slug: "extension-maintenance",
    name: "Extension Maintenance",
    description: "Repositioning, refresh, and tightening.",
    category: "extensions" as ServiceCategory,
    duration_min: 105,
    price_cents: 24000,
    deposit_cents: 6000,
    requires_consult: false,
    is_active: true,
    sort_order: 3,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$165–$315",
    durationDisplay: "90–120 min",
  },

  // ── ADD-ONS ─────────────────────────────────────────────────────────────────
  {
    id: "00000000-0000-0000-0000-000000000036",
    slug: "scalp-massage-upgrade",
    name: "Scalp Massage Upgrade",
    description: "Extended scalp massage added to any service.",
    category: "add-ons" as ServiceCategory,
    duration_min: 10,
    price_cents: 2000,
    deposit_cents: 0,
    requires_consult: false,
    is_active: true,
    sort_order: 1,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$20",
    durationDisplay: "+10 min",
  },
  {
    id: "00000000-0000-0000-0000-000000000037",
    slug: "express-blowout-addon",
    name: "Express Blowout (after color)",
    description: "Blowout and style added on after any color service.",
    category: "add-ons" as ServiceCategory,
    duration_min: 30,
    price_cents: 4250,
    deposit_cents: 0,
    requires_consult: false,
    is_active: true,
    sort_order: 2,
    created_at: new Date(0).toISOString(),
    priceDisplay: "$35–$50",
    durationDisplay: "+30 min",
  },
];

// Helpers used by the booking flow and site
export const servicesByCategory = services.reduce<
  Record<string, ServiceWithDisplay[]>
>((acc, s) => {
  if (!acc[s.category]) acc[s.category] = [];
  acc[s.category].push(s);
  return acc;
}, {});

export const serviceBySlug = Object.fromEntries(
  services.map((s) => [s.slug, s])
);

export const categoryOrder: ServiceCategory[] = [
  "cuts",
  "color",
  "treatments",
  "styling",
  "extensions",
  "add-ons",
];

export const categoryLabels: Record<ServiceCategory, string> = {
  cuts: "Cuts",
  color: "Color",
  treatments: "Treatments",
  styling: "Styling",
  extensions: "Extensions",
  "add-ons": "Add-ons",
};
